server:
  port: 9000


eureka:
  instance:
    appname: CENTERLIZED-SWAGGER
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

swagger:
  config:
    refreshrate: 50000
    
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher    
