server:
  port: 8083
spring:
  application:
    name: HOTEL-SERVICE
eureka:
  instance:
    ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
#okta config for api gateway
okta: 
  oauth2:
    issuer: https://dev-52669198.okta.com/oauth2/default
    audience: api://default
    
    
    