
server:
  port: 8082

spring:
  application:
    name: USER-SERVICE
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8085}/
      
#eureka:
#  instance:
 #   prefer-ip-address: true
 # client:
 #   fetch-registry: true
  #  register-with-eureka: true
  #  service-url:
  #    defaultZone: http://localhost:8761/eureka