server:
  port: 8084

spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      database: MicroServices
      uri: mongodb+srv://rgrohitoist:P%40sswd%403@microservices.ffquqor.mongodb.net/MicroServices
      port: 27017

eureka:
  instance:
    ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
#okta config for api gateway
okta: 
  oauth2:
    issuer: https://dev-52669198.okta.com/oauth2/default
    audience: api://default